import { createContext, useContext, useState } from "react";

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
    const [lang, setLang] = useState("en");
    const toggleLang = () => setLang((l) => (l === "en" ? "ur" : "en"));

    return (
        <LanguageContext.Provider value={{ lang, toggleLang }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const ctx = useContext(LanguageContext);
    if (!ctx) throw new Error("useLanguage must be used inside LanguageProvider");
    return ctx;
}

export const TRANSLATIONS = {
    en: {
        // ── Layout & Nav ──────────────────────────────────────────
        switchLang: "اردو",
        signOut: "Sign Out",
        search: "Search crops, irrigation, soil…",
        dashboard: "Dashboard",
        browseRepo: "Browse Repository",
        aiAssistant: "AI Assistant",
        profile: "Profile",
        home: "Home",
        about: "About Us",
        resources: "Resources",
        contact: "Contact Us",

        // ── Dashboard ──────────────────────────────────────────────
        welcomeBadge: "🌿 Welcome to AgriChat",
        heroTitle1: "Paedar Qudratti",
        heroTitle2: "Nizam-e-Kashtari",
        heroDesc: "Pakistan's pioneering sustainable natural farming methodology, developed to free smallholder farmers from chemical dependency through science-backed, nature-first agriculture.",
        askAI: "🤖 Ask AI Assistant",
        browseRepository: "📚 Browse Repository",
        pakAgriResearch: "Pakistan Agriculture Research",
        estBy: "Est. Dr. Asif Sharif",
        benefit0: "Reduction in water usage",
        benefit1: "Lower input costs vs conventional",
        benefit2: "Improvement in soil organic matter",
        benefit3: "Synthetic chemicals used",
        founderRole: "Founder, PQNK",
        founderTitle2: "Agronomist · Researcher",
        founderSectionTitle: "🎓 The Visionary Behind PQNK",
        founderBio1: "Dr. Asif Sharif is a Pakistani agronomist whose decades of research led to the formulation of PQNK — a complete natural farming system tailored to Pakistan's soil types, climate zones, and cultural farming practices.",
        founderBio2: "Working in partnership with Pakistan Agriculture Research (PAR), Dr. Sharif has demonstrated PQNK on hundreds of farms across Punjab and Sindh, showing that sustainable yields without chemicals are not just possible — they are economically superior.",
        pillarsTitle: "The 6 Pillars of PQNK",
        pillarsSubtitle: "Natural · Sustainable · Pakistani",
        pillar0Title: "Natural Soil Rejuvenation",
        pillar0Desc: "PQNK eliminates synthetic fertilizers by rebuilding soil microbiomes through compost, vermicompost, and natural mulching — restoring long-term fertility without chemical dependency.",
        pillar0Tag: "Soil Health",
        pillar1Title: "Water Conservation",
        pillar1Desc: "Precision irrigation guided by soil moisture indicators and crop cycles reduces water usage by up to 40% compared to conventional flood irrigation practices.",
        pillar1Tag: "Irrigation",
        pillar2Title: "Biological Pest Control",
        pillar2Desc: "Neem-based sprays, companion planting, and beneficial insect habitats replace chemical pesticides — protecting crops while maintaining ecological balance.",
        pillar2Tag: "Pest Control",
        pillar3Title: "Seed Sovereignty",
        pillar3Desc: "PQNK promotes traditional, open-pollinated Pakistani seed varieties — preserving genetic diversity and freeing farmers from corporate seed dependency.",
        pillar3Tag: "Seeds",
        pillar4Title: "Knowledge Integration",
        pillar4Desc: "Ancient farming wisdom is validated through modern agronomic science, creating a methodology that is both culturally rooted and evidence-based.",
        pillar4Tag: "Research",
        pillar5Title: "Community Farming",
        pillar5Desc: "Collective knowledge-sharing networks among farmers amplify PQNK adoption, creating village-level agricultural communities that support each other.",
        pillar5Tag: "Community",
        cropsTitle: "Crops in the PQNK System",
        cropRabi: "Rabi (Winter)",
        cropKharif: "Kharif (Summer)",
        cropYearRound: "Year-round",
        cropSeasonal: "Seasonal",
        ctaTitle: "Have an agricultural question?",
        ctaDesc: "Our AI assistant is trained on the full PQNK knowledge base — ask anything about crops, soil, irrigation, or pest control.",
        ctaBtn: "🤖 Open AI Assistant",

        // ── About Us ───────────────────────────────────────────────
        aboutHeroBadge: "🌿 About PQNK",
        aboutHeroTitle: "Paedar Qudratti Nizam-e-Kashtari",
        aboutHeroDesc1: "PQNK — pronounced 'picnic' — is the abbreviation of Paedar Qudratti Nizam Kashatqari, meaning Sustainable Natural Farming System in Urdu.",
        aboutHeroDesc2: "It is also referred to as Paradoxical Agriculture — a pioneering methodology that replicates natural dynamics in agricultural production, eliminating synthetic chemicals while achieving superior yields.",
        aboutWhatIsTitle: "What is PQNK?",
        aboutWhatIsDesc1: "PQNK is the abbreviation of Paedar Qudratti Nizam Kashatqari — a sustainable natural farming system in Urdu, also referred to as Paradoxical Agriculture. Mr. Asif Sharif has conceptualised PQNK through first-hand experience on his own land in the Indo-Gangetic Plains of Pakistan.",
        aboutWhatIsDesc2: "He later founded Pedaver, a company that works with thousands of farmers to disseminate the PQNK system and develop appropriate mechanisation. Initially, after identifying that inundation, soil disturbance, and bare land are contrary to the natural processes of soil fertility and vegetation, Mr. Asif developed the raised bed planting system.",
        aboutWhatIsDesc3: "Rice was the first crop tested on Asif's raised beds — conventionally grown under flooded conditions. This was to demonstrate that water serves as a nutrient carrier, and only the water absorbed by the roots and transpired from the leaves is needed for plant development.",
        aboutWhatIsDesc4: "At this stage, Asif gained insights into optimal plant population — row spacing and plant-to-plant distance. After achieving success by reducing rice plant density, the next objective was to maintain soil coverage. Rice crop residues had been utilised for this purpose.",
        aboutWhatIsDesc5: "Soon PQNK developed into a more comprehensive farming method for all crops and trees that combines SRI and Conservation Agriculture (CA), with natural farming as an overarching principle.",
        aboutCorePrinciplesTitle: "Core Principles",
        aboutPrinciple0: "Zero Synthetic Amendments",
        aboutPrinciple0Desc: "No chemical fertilisers or pesticides",
        aboutPrinciple1: "Permanent Raised Beds",
        aboutPrinciple1Desc: "No-till, non-compacted raised bed system",
        aboutPrinciple2: "70%+ Water Reduction",
        aboutPrinciple2Desc: "Precision moisture management",
        aboutPrinciple3: "Organic Mulch Cover",
        aboutPrinciple3Desc: "Permanent biomass on soil surface",
        aboutPrinciple4: "Optimal Plant Spacing",
        aboutPrinciple4Desc: "Adapted density for natural soil fertility",
        aboutPrinciple5: "Agro-biodiversity",
        aboutPrinciple5Desc: "Intercropping, trees, and diversification",
        aboutPracticesTitle: "PQNK Agricultural Practices",
        aboutPractice0Title: "PQNK Agricultural Practices",
        aboutPractice0Desc: "Under PQNK, crops are cultivated on permanent no-till raised beds that are formed on levelled, non-compacted land. The beds' size is adapted to the size of the tractor and machinery wheels, so that the wheels are driving through the furrows, hence not compacting the beds. Beds are covered with organic mulch that can be locally procured by leaving previous crop residues on the field.",
        aboutPractice1Title: "Why Raised Beds?",
        aboutPractice1Desc: "Growing crops on raised beds minimises soil disturbance to protect soil biota, improves soil structure, and promotes carbon sequestration. With machines developed to the size of the raised beds, PQNK facilitates the large-scale implementation of no-till. In PQNK, soil compaction is completely avoided by letting the tires of the heavy machinery drive in the furrows between the beds.",
        aboutPractice2Title: "Why Organic Mulch?",
        aboutPractice2Desc: "In a PQNK system, the layer of organic mulch should be thick enough to cover the soil surface and prevent sunlight from reaching the soil. This inhibits weed germination, resulting in a non-chemical strategy for weed management. Maintaining permanent biomass cover on the soil surface also protects the land from overheating in direct sunlight, which adversely affects the soil biota.",
        aboutPractice3Title: "Why Optimise Plant Spacing?",
        aboutPractice3Desc: "Increasing the spacing between plants — reducing plant density per m² — should be done when soil is managed according to the principles of Conservation Agriculture (CA) as in PQNK systems. This is because it is natural for tillering crops to grow more profusely in the more fertile soil environment created by PQNK practices: more soil organic matter, more soil microbiome activity.",
        aboutPractice4Title: "Why Diversification?",
        aboutPractice4Desc: "Promoting diversification within the farming system increases biodiversity and results in greater land use efficiency and higher overall farm yield while enhancing carbon sequestration, especially when trees are included. Within a PQNK system, it is important to consider multiple strategies for achieving greater crop biodiversity — introducing cover crops between seasons, intercropping, alley cropping, relay cropping.",
        aboutPractice5Title: "What is Mechanisation?",
        aboutPractice5Desc: "Pedaver has developed machinery for mechanically forming raised beds and furrows, and for mechanised direct planting through heavy mulch with precise plant spacing. Transplanting of young single seedlings in permanent no-till raised beds with precise spacing is also possible thanks to Pedaver's innovations. Recent machinery even allows for forming the raised permanent beds while direct seeding in one single passage.",
        aboutMissionTitle: "Our Mission",
        aboutMission0Title: "Scale Expert Knowledge",
        aboutMission0Desc: "Digitise Dr. Sharif's PQNK expertise — accessible to every farmer in Pakistan 24/7, in Urdu and English.",
        aboutMission1Title: "AI-Powered Accessibility",
        aboutMission1Desc: "Through RAG-powered AI, provide reliable, hallucination-free agronomic guidance grounded entirely in the PQNK knowledge corpus.",
        aboutMission2Title: "Sustainable Agriculture",
        aboutMission2Desc: "Equip Pakistan's 37% agricultural workforce with tools to transition from chemical-dependent farming to natural, sustainable practices.",
        aboutFounderTitle: "Meet the Founder",
        aboutFounderHeroTitle: "A Trailblazing Innovator",
        aboutFounderName: "Mr. Asif Sharif",
        aboutFounderRole: "Founder & Chairman — Pedaver",
        aboutFounderBio1: "Mr. Asif Sharif is a visionary and innovative agricultural pioneer, entrepreneur, engineer, inventor, and philanthropist. Born into the esteemed SirGroh family of Faisalabad, renowned for its contributions to education, agriculture, and community service, Mr. Sharif has upheld the family's legacy and virtues.",
        aboutFounderBio2: "His expertise encompasses marketing, project development in agriculture, production process development & mechanisation, forward engineering, alternate energies, value addition, and responsible citizenship. He has transformed numerous farms by implementing sound programmes for mechanisation, management, farm design, irrigation, and knowledge-based skills development.",
        aboutFounderMachineryTitle: "Machinery & Innovation",
        aboutFounderMachineryDesc1: "Mr. Sharif has revolutionised the agricultural industry with numerous inventions. He designed, developed, and introduced a multitude of agricultural machinery including soil scrapers, fine levellers, ridgers, reversible disc ploughs, plate planters, tractor mounted sprayers, sugarcane planters, stubble shavers, combine harvesters, cotton pickers, and peanut harvesters.",
        aboutFounderMachineryDesc2: "His ingenuity extends to machinery for land levelling, customised precision laser levelling, raised-bed cropping, precision seeding, compost banding, fertiliser side dressing, transplanting, weeding, and soil aerating. He introduced improved seeds and hybrids of Corn, Cotton, and Sunflower.",
        aboutFounderInitiativesTitle: "Groundbreaking Initiatives",
        aboutFounderInitiativesDesc1: "Mr. Sharif challenged the conventional tillage-based crop production process used for millennia. He developed the PQNK system which requires no tillage or agrochemicals and reduces water use by over 70%. It produces food at the lowest cost and highest quality, surpassing even organic standards.",
        aboutFounderInitiativesDesc2: "He developed a method for growing rice on raised beds in moist soil, achieving a remarkable 70% reduction in water usage. Additionally, he spearheaded the \"One Acre Prosperity\" (OAP) process, empowering smallholders to achieve financial independence.",
        aboutTimelineTitle: "Career Timeline",
        aboutBusinessTitle: "Business & Diplomacy",
        aboutBusinessDesc1: "Beyond his technical expertise, Mr. Sharif has made significant contributions to business and agriculture. He served as President of the Pakistan-Belgium Business Development Forum, Honorary Consul for the Republic of Poland, and a member of the Board of Directors of Zarai Taraqiati Bank.",
        aboutBusinessDesc2: "He played a pivotal role in introducing renowned global companies to Pakistan, including Ford Motor Company, Sperry New Holland, Ford New Holland, Case IH, Toft, Long Manufacturing, Butler, Howard, Ursus, and Kenwood.",
        aboutPhilanthropyTitle: "Philanthropy & Values",
        aboutPhilanthropyDesc1: "Mr. Sharif is a global citizen who has undergone training in the United States, Australia, and Europe, travelling across five continents for study, training, business, and research. He is a trustworthy and compassionate leader earning the respect of colleagues and communities he serves.",
        aboutPhilanthropyDesc2: "He is particularly passionate about animal welfare, life in the soil, and all lifeforms — embodying a wholistic philosophy of ecological stewardship extending far beyond agriculture.",
        aboutCollaborationTitle: "In Collaboration With",

        // ── Contact Us ──────────────────────────────────────────────
        contactHeroBadge: "📬 Contact Us",
        contactHeroTitle: "Get in Touch",
        contactHeroDesc: "Have questions about PQNK, the platform, collaboration opportunities, or research enquiries? We'd love to hear from you — let's start a conversation.",
        contactInfoTitle: "Contact Information",
        contactLabel0: "Affiliated Institution",
        contactLabel1: "Industry Partner",
        contactLabel2: "Research Enquiries",
        contactLabel3: "Academic Conference",
        contactFollowTitle: "Follow Our Research",
        contactFormTitle: "Send Us a Message",
        contactFormIntro: "All fields marked with * are required.",
        contactFirstName: "First Name",
        contactLastName: "Last Name",
        contactEmail: "Email Address",
        contactPhone: "Phone Number",
        contactSubject: "Subject",
        contactMessage: "Message",
        contactSubjectSelect: "Select a topic…",
        contactSubjectGeneral: "General Enquiry",
        contactSubjectPQNK: "PQNK Farming Practices",
        contactSubjectResearch: "Research & Academic Collaboration",
        contactSubjectTechnical: "Platform / Technical Support",
        contactSubjectMedia: "Media & Press",
        contactSubjectOther: "Other",
        contactSendBtn: "📤 Send Message",
        contactSendingBtn: "Sending…",
        contactSuccessTitle: "Message Sent!",
        contactSuccessDesc: "Thank you for reaching out. Our team will review your message and respond within 2–3 business days.",
        contactAnotherBtn: "Send Another Message",

        // ── Profile ────────────────────────────────────────────────
        profileTitle: "My Profile",
        profileDesc: "Manage your account information and credentials",
        profileMemberSince: "Member Since",
        profileStatus: "Status",
        profileOnline: "Online",
        profileAccountDetails: "Account Details",
        profileEditBtn: "✏️ Edit Profile",
        profileUpdateSuccess: "Profile updated successfully!",
        profileUpdateFail: "Update failed",
        profileServerErr: "Could not connect to server",
        profileFullName: "Full Name",
        profileEmailLock: "Email Address (cannot be changed)",
        profileChangePass: "Change Password (leave blank to keep current)",
        profileCurrentPass: "Current Password",
        profileNewPass: "New Password",
        profileConfirmPass: "Confirm New Password",
        profileSaveBtn: "Save Changes",
        profileCancelBtn: "Cancel",
        profileSavingBtn: "Saving…",
        profilePassMismatch: "New passwords do not match",

        // ── User Survey ────────────────────────────────────────────
        surveyTitle: "Help Us Understand You Better",
        surveyTitleDone: "✅ Survey Completed — Thank You!",
        surveyDesc: "A quick 6-question survey to help us serve farmers better (2 min)",
        surveyDescDone: "Your responses have been saved. Click to review or update.",
        surveyUpdateMsg: "✅ Your responses are saved. You may update them at any time.",
        surveyQ1: "1. Farm / Land Holding Size",
        surveyQ1Select: "Select land size…",
        surveyQ1Opt1: "Less than 1 acre",
        surveyQ1Opt2: "1 – 5 acres",
        surveyQ1Opt3: "5 – 20 acres",
        surveyQ1Opt4: "20 – 50 acres",
        surveyQ1Opt5: "More than 50 acres",
        surveyQ1Opt6: "No land (student / researcher)",
        surveyQ2: "2. Primary Crops Grown (select all that apply)",
        surveyQ3: "3. Your Biggest Farming Challenge",
        surveyQ3Select: "Select main challenge…",
        surveyQ3Opt1: "Water access / irrigation",
        surveyQ3Opt2: "Pest & disease control",
        surveyQ3Opt3: "Soil health / fertility",
        surveyQ3Opt4: "Market access / pricing",
        surveyQ3Opt5: "Financing / credit",
        surveyQ3Opt6: "Lack of agricultural knowledge",
        surveyQ3Opt7: "Climate change / weather",
        surveyQ3Opt8: "Labour availability",
        surveyQ3Opt9: "Other",
        surveyQ4: "4. How Did You Hear About PQNK / AgriChat?",
        surveyQ4Select: "Select source…",
        surveyQ4Opt1: "YouTube video by Mr. Asif Sharif",
        surveyQ4Opt2: "WhatsApp group / broadcast",
        surveyQ4Opt3: "PAR extension worker / event",
        surveyQ4Opt4: "Word of mouth (farmer, friend)",
        surveyQ4Opt5: "Social media (Facebook, Instagram)",
        surveyQ4Opt6: "University / academic context",
        surveyQ4Opt7: "Pedaver / field demonstration",
        surveyQ4Opt8: "Other",
        surveyQ5: "5. Years of Farming Experience",
        surveyQ5Select: "Select experience level…",
        surveyQ5Opt1: "No farming experience",
        surveyQ5Opt2: "1 – 3 years",
        surveyQ5Opt3: "3 – 10 years",
        surveyQ5Opt4: "10 – 25 years",
        surveyQ5Opt5: "More than 25 years",
        surveyQ6: "6. Reading / Literacy Level (helps us optimise the platform for you)",
        surveyQ6Opt1: "I can read and write comfortably in English or Urdu",
        surveyQ6Opt2: "I am partially literate — I prefer simple language",
        surveyQ6Opt3: "I prefer audio responses — I rely on listening rather than reading",
        surveySubmitBtn: "✅ Submit Survey",
        surveyUpdateBtn: "💾 Update Survey Responses",

        // ── Chatbot ──────────────────────────────────────────────
        newConversation: "New Conversation",
        quickTopics: "Quick Topics",
        recentConversations: "Recent Conversations",
        noConversations: "No past conversations",
        online: "Online · Powered by PQNK IntelliAgri",
        welcomeTitle: "Welcome to AgriChat",
        welcomeBody: "I'm trained on extensive agricultural datasets covering crops, soil science, irrigation, climate adaptation, pest management, and more. Ask me anything — from basic farming to advanced agronomic planning.",
        placeholder: "Type your message…",
        thinking: "AgriChat is thinking…",
        enterHint: "Enter to send · Shift+Enter new line",
        recording: "Recording… tap mic to stop",
        transcribing: "Transcribing…",
        voiceErr: "Voice input failed. Please try again.",
        suggestedQ: "Suggested Questions",
        topicCrop: "Crop Problem",
        topicWater: "When to Water?",
        topicFert: "Fertilizer Info",
        topicPest: "Pest Control",
        promptWheat: "Wheat Irrigation",
        promptSoil: "Soil Health",
        promptPest: "Cotton Pests",
        promptRice: "Rice Yield",
        promptNursery: "Seedling Care",
        queryCrop: "I have a problem with my crop. Can you help me diagnose it?",
        queryWater: "What is the best irrigation schedule for my current crops?",
        queryFert: "How should I manage fertilizers for better soil health?",
        queryPest: "What are the common pests I should look out for and how to control them?",
        queryWheat: "What is the best irrigation schedule for wheat crops in the PQNK system?",
        querySoil: "How can I improve soil fertility naturally without chemical fertilizers?",
        queryPestCot: "What are organic pest control methods for cotton crops in Pakistan?",
        queryRice: "How can I optimize crop yield for rice using permanent raised beds?",
        queryNursery: "What are the best practices for seedling care and nursery management?",
        
        // ── Auth Pages ─────────────────────────────────────────────
        authWelcomeBack: "Welcome back",
        authSignInDesc: "Sign in to continue to your dashboard",
        authEmailLabel: "Email Address",
        authEmailPlaceholder: "you@example.com",
        authPasswordLabel: "Password",
        authForgotPassword: "Forgot password?",
        authRememberMe: "Remember me",
        authSignInBtn: "Sign In",
        authSigningIn: "Signing in…",
        authOr: "or",
        authNoAccount: "Don't have an account?",
        authCreateAccount: "Create Account",
        
        authCreateTitle: "Create an Account",
        authCreateDesc: "Join PQNK to access natural farming insights.",
        authFullName: "Full Name",
        authFullNamePlace: "Dr. Asif Sharif",
        authPhoneLabel: "Phone Number",
        authPhonePlace: "0300 1234567",
        authConfirmPassword: "Confirm Password",
        authAgreeTerms1: "I agree to the",
        authAgreeTerms2: "Terms of Service",
        authAgreeTerms3: "and",
        authAgreeTerms4: "Privacy Policy",
        authSignUpBtn: "Create Account",
        authSigningUp: "Creating account…",
        authHaveAccount: "Already have an account?",
        authLoginLink: "Log In",
        
        authVerifyTitle: "Verify Your Account",
        authVerifyDesc1: "We sent a 6-digit verification code to",
        authVerifyDesc2: "Please enter it below to activate your account.",
        authCodeLabel: "Verification Code",
        authVerifyBtn: "Verify Account",
        authVerifying: "Verifying…",
        authDidntReceive: "Didn't receive the code?",
        authResendBtn: "Resend Code",
        authResending: "Resending…",
        authBackToLogin: "Back to Login",
        
        authResetTitle: "Reset Password",
        authResetDesc: "Enter your email address and we'll send you a 6-digit code to reset your password.",
        authSendCodeBtn: "Send Reset Code",
        authSendingCode: "Sending…",
        authVerifyResetTitle: "Verify & Reset",
        authVerifyResetDesc: "Enter the code sent to your email and your new password.",
        authResetNewPass: "New Password",
        authResetBtn: "Reset Password",
        authResetting: "Resetting…",
    },

    ur: {
        // ── Layout & Nav ──────────────────────────────────────────
        switchLang: "EN",
        signOut: "سائن آؤٹ",
        search: "فصلیں، آبپاشی، مٹی تلاش کریں…",
        dashboard: "ڈیش بورڈ",
        browseRepo: "ذخیرہ دیکھیں",
        aiAssistant: "AI اسسٹنٹ",
        profile: "پروفائل",
        home: "ہوم",
        about: "ہمارے بارے میں",
        resources: "وسائل",
        contact: "رابطہ کریں",

        // ── Dashboard ──────────────────────────────────────────────
        welcomeBadge: "🌿 ایگری چیٹ میں خوش آمدید",
        heroTitle1: "پائیدار قدرتی",
        heroTitle2: "نظامِ کاشتکاری",
        heroDesc: "PQNK — پاکستان کا اہم پائیدار قدرتی کاشتکاری نظام، جو چھوٹے کسانوں کو کیمیائی انحصار سے آزاد کرنے کے لیے سائنسی بنیادوں اور قدرتی طریقوں پر تیار کیا گیا ہے۔",
        askAI: "🤖 AI اسسٹنٹ سے پوچھیں",
        browseRepository: "📚 ذخیرہ دیکھیں",
        pakAgriResearch: "پاکستان ایگریکلچر ریسرچ",
        estBy: "بانی: ڈاکٹر آصف شریف",
        benefit0: "پانی کے استعمال میں کمی",
        benefit1: "روایتی طریقوں کے مقابلے میں کم اخراجات",
        benefit2: "مٹی میں نامیاتی مادے میں بہتری",
        benefit3: "مصنوعی کیمیکل استعمال نہیں",
        founderRole: "بانی، PQNK",
        founderTitle2: "ماہرِ زراعت · محقق",
        founderSectionTitle: "🎓 PQNK کے پیچھے وژن",
        founderBio1: "ڈاکٹر آصف شریف ایک پاکستانی ماہرِ زراعت ہیں جن کی دہائیوں کی تحقیق نے PQNK کو جنم دیا — ایک مکمل قدرتی کاشتکاری نظام جو پاکستان کی مٹی، آب و ہوا اور ثقافتی زرعی طریقوں کے مطابق ڈھالا گیا ہے۔",
        founderBio2: "پاکستان ایگریکلچر ریسرچ (PAR) کے ساتھ شراکت میں، ڈاکٹر شریف نے پنجاب اور سندھ کے سینکڑوں کھیتوں میں PQNK کا مظاہرہ کیا ہے، یہ ثابت کرتے ہوئے کہ بغیر کیمیکلز کے پائیدار پیداوار نہ صرف ممکن ہے بلکہ اقتصادی لحاظ سے بھی بہتر ہے۔",
        pillarsTitle: "PQNK کے 6 ستون",
        pillarsSubtitle: "قدرتی · پائیدار · پاکستانی",
        pillar0Title: "مٹی کی قدرتی بحالی",
        pillar0Desc: "PQNK کھاد، ورمی کمپوسٹ اور قدرتی ملچنگ کے ذریعے مٹی کے خرد حیاتیات کو بحال کرکے مصنوعی کھادوں کو ختم کرتا ہے — کیمیائی انحصار کے بغیر طویل مدتی زرخیزی بحال کرتا ہے۔",
        pillar0Tag: "مٹی کی صحت",
        pillar1Title: "پانی کا تحفظ",
        pillar1Desc: "مٹی کی نمی اور فصل کے چکروں پر مبنی درست آبپاشی روایتی سیلابی آبپاشی کے مقابلے میں پانی کے استعمال کو 40٪ تک کم کرتی ہے۔",
        pillar1Tag: "آبپاشی",
        pillar2Title: "حیاتیاتی کیٹ کنٹرول",
        pillar2Desc: "نیم پر مبنی اسپرے، ساتھی پودے لگانے اور فائدہ مند کیڑوں کی پناہ گاہیں کیمیائی کیٹ ماری کی جگہ لیتی ہیں — ماحولیاتی توازن برقرار رکھتے ہوئے فصلوں کی حفاظت کرتی ہیں۔",
        pillar2Tag: "کیٹ کنٹرول",
        pillar3Title: "بیج کی خودمختاری",
        pillar3Desc: "PQNK روایتی، کھلے پولینیٹڈ پاکستانی بیج کی اقسام کو فروغ دیتا ہے — جینیاتی تنوع کو محفوظ رکھتا ہے اور کسانوں کو کارپوریٹ بیج پر انحصار سے آزاد کرتا ہے۔",
        pillar3Tag: "بیج",
        pillar4Title: "علم کا انضمام",
        pillar4Desc: "قدیم کاشتکاری کی حکمت کو جدید زرعی سائنس کے ذریعے تصدیق کیا گیا ہے، ایک ایسا طریقہ کار بنایا گیا ہے جو ثقافتی جڑوں سے جڑا ہے اور شواہد پر مبنی بھی ہے۔",
        pillar4Tag: "تحقیق",
        pillar5Title: "اجتماعی کاشتکاری",
        pillar5Desc: "کسانوں کے درمیان اجتماعی علم کے تبادلے کے نیٹ ورک PQNK کو فروغ دیتے ہیں، گاؤں کی سطح کی زرعی کمیونٹیاں بناتے ہیں جو ایک دوسرے کی مدد کرتے ہیں۔",
        pillar5Tag: "کمیونٹی",
        cropsTitle: "PQNK نظام میں فصلیں",
        cropRabi: "ربیع (سردیوں)",
        cropKharif: "خریف (گرمیوں)",
        cropYearRound: "سال بھر",
        cropSeasonal: "موسمی",
        ctaTitle: "کوئی زرعی سوال ہے؟",
        ctaDesc: "ہمارا AI اسسٹنٹ مکمل PQNK علمی بنیاد پر تربیت یافتہ ہے — فصلوں، مٹی، آبپاشی یا کیٹ کنٹرول کے بارے میں کچھ بھی پوچھیں۔",
        ctaBtn: "🤖 AI اسسٹنٹ کھولیں",

        // ── About Us ───────────────────────────────────────────────
        aboutHeroBadge: "🌿 PQNK کے بارے میں",
        aboutHeroTitle: "پائیدار قدرتی نظامِ کاشتکاری",
        aboutHeroDesc1: "PQNK — جس کا تلفظ 'پک نک' (picnic) ہے — پائیدار قدرتی نظام کاشتکاری کا مخفف ہے۔",
        aboutHeroDesc2: "اسے 'پیراڈاکسیکل ایگریکلچر' بھی کہا جاتا ہے — یہ ایک ایسا انقلابی طریقہ کار ہے جو زرعی پیداوار میں قدرتی حرکیات کی نقل کرتا ہے، مصنوعی کیمیکلز کو ختم کرتا ہے اور بہترین پیداوار حاصل کرتا ہے۔",
        aboutWhatIsTitle: "PQNK کیا ہے؟",
        aboutWhatIsDesc1: "PQNK پائیدار قدرتی نظام کاشتکاری کا مخفف ہے، جسے اردو میں پیراڈاکسیکل ایگریکلچر بھی کہا جاتا ہے۔ مسٹر آصف شریف نے پاکستان کے میدانی علاقوں میں اپنی زمین پر براہِ راست تجربے کے ذریعے PQNK کا تصور پیش کیا ہے۔",
        aboutWhatIsDesc2: "انہوں نے بعد میں پداور (Pedaver) کی بنیاد رکھی، ایک ایسی کمپنی جو ہزاروں کسانوں کے ساتھ مل کر PQNK نظام کو پھیلانے اور مناسب مشینری تیار کرنے کے لیے کام کرتی ہے۔ شروع میں، یہ پہچاننے کے بعد کہ زمین کو پانی میں ڈبونا، مٹی کو چھیڑنا اور ننگی زمین رکھنا مٹی کی زرخیزی اور پودوں کے قدرتی عمل کے خلاف ہے، مسٹر آصف نے اٹھائے ہوئے بیڈ (Raised Bed) کا کاشتکاری نظام تیار کیا۔",
        aboutWhatIsDesc3: "چاول پہلی فصل تھی جس کا تجربہ آصف کے اٹھائے ہوئے بیڈز پر کیا گیا — جو روایتی طور پر سیلابی حالات میں اگائی جاتی ہے۔ اس کا مقصد یہ ثابت کرنا تھا کہ پانی صرف غذائی اجزاء کے حامل کے طور پر کام کرتا ہے، اور پودے کی نشوونما کے لیے صرف جڑوں سے جذب ہونے والا اور پتوں سے اخراج ہونے والا پانی درکار ہوتا ہے۔",
        aboutWhatIsDesc4: "اس مرحلے پر، آصف نے پودوں کی بہترین تعداد — قطاروں کے درمیان فاصلہ اور پودے سے پودے کے فاصلے — کے بارے میں آگاہی حاصل کی۔ چاول کے پودوں کی کثافت کم کرکے کامیابی حاصل کرنے کے بعد، اگلا ہدف مٹی کی سطح کو ڈھانپ کر رکھنا تھا۔ اس مقصد کے لیے چاول کی فصل کی باقیات استمال کی گئیں۔",
        aboutWhatIsDesc5: "جلد ہی PQNK تمام فصلوں اور درختوں کے لیے ایک جامع کاشتکاری طریقہ کار میں تبدیل ہو گیا جو SRI اور کنزرویشن ایگریکلچر (CA) کو یکجا کرتا ہے، جس میں قدرتی کاشتکاری ایک بنیادی اصول ہے۔",
        aboutCorePrinciplesTitle: "بنیادی اصول",
        aboutPrinciple0: "مصنوعی کیمیکلز سے پاک",
        aboutPrinciple0Desc: "کوئی کیمیائی کھاد یا کیڑے مار ادویات نہیں",
        aboutPrinciple1: "مستقل اٹھائے ہوئے بیڈز",
        aboutPrinciple1Desc: "بغیر ہل چلائے (No-till)، سخت نہ ہونے والا بیڈ سسٹم",
        aboutPrinciple2: "70٪ سے زیادہ پانی کی بچت",
        aboutPrinciple2Desc: "نمی کا درست انتظام",
        aboutPrinciple3: "نامیاتی ملچ کا احاطہ",
        aboutPrinciple3Desc: "مٹی کی سطح پر مستقل حیاتیاتی ڈھانپ",
        aboutPrinciple4: "پودوں کا بہترین فاصلہ",
        aboutPrinciple4Desc: "قدرتی زرخیزی کے مطابق پودوں کی تعداد",
        aboutPrinciple5: "زرعی حیاتیاتی تنوع",
        aboutPrinciple5Desc: "مخلوط کاشت کاری (Intercropping) اور درخت",
        aboutPracticesTitle: "PQNK زرعی طریقہ کار",
        aboutPractice0Title: "PQNK زرعی طریقہ کار",
        aboutPractice0Desc: "PQNK کے تحت، فصلیں مستقل بغیر ہل چلائے (no-till) اٹھائے ہوئے بیڈز پر کاشت کی جاتی ہیں جو ہموار اور غیر سخت زمین پر بنتے ہیں۔ بیڈز کا سائز ٹریکٹر اور مشینری کے پہیوں کے سائز کے مطابق ہوتا ہے، تاکہ پہیے نالیوں (furrows) میں چلیں اور بیڈز سخت نہ ہوں۔ بیڈز کو نامیاتی ملچ (organic mulch) سے ڈھانپا جاتا ہے، جو پچھلی فصل کی باقیات کو کھیت میں چھوڑ کر حاصل کیا جا سکتا ہے۔",
        aboutPractice1Title: "اٹھائے ہوئے بیڈز کیوں؟",
        aboutPractice1Desc: "اٹھائے ہوئے بیڈز پر فصلیں اگانے سے مٹی میں مداخلت کم ہوتی ہے، مٹی کے جاندار محفوظ رہتے ہیں، مٹی کی ساخت بہتر ہوتی ہے، اور کاربن کے جذب ہونے (sequestration) کو فروغ ملتا ہے۔ آصف شریف کی ایجاد کردہ مشینری کے ساتھ، PQNK بڑے پیمانے پر بغیر ہل چلائے کاشتکاری کو آسان بناتا ہے۔ PQNK میں، مشینری کے بھاری ٹائروں کو بیڈز کے درمیان نالیوں میں چلا کر مٹی کو سخت ہونے سے مکمل طور پر بچایا جاتا ہے۔",
        aboutPractice2Title: "نامیاتی ملچ کیوں؟",
        aboutPractice2Desc: "PQNK نظام میں، نامیاتی ملچ کی تہہ اتنی موٹی ہونی چاہیے جو مٹی کی سطح کو ڈھانپ لے اور سورج کی روشنی کو مٹی تک پہنچنے سے روکے۔ اس سے جڑی بوٹیوں کے اگنے میں رکاوٹ پیدا ہوتی ہے، جس کے نتیجے میں جڑی بوٹیوں کے انتظام کے لیے ایک غیر کیمیائی حکمت عملی حاصل ہوتی ہے۔ مٹی کی سطح پر مستقل ملچ سورج کی براہِ راست روشنی سے زمین کو زیادہ گرم ہونے سے بھی بچاتی ہے، جو مٹی کے جانداروں پر منفی اثر ڈالتی ہے۔",
        aboutPractice3Title: "پودوں کے فاصلے کو بہتر کیوں بنائیں؟",
        aboutPractice3Desc: "پودوں کے درمیان فاصلہ بڑھانا — یعنی فی مربع میٹر پودوں کی تعداد کم کرنا — تب کیا جانا چاہیے جب مٹی کا انتظام کنزرویشن ایگریکلچر (CA) کے اصولوں کے مطابق ہو جیسے PQNK میں ہوتا ہے۔ یہ اس لیے ہے کہ PQNK طریقوں سے پیدا ہونے والے زیادہ زرخیز مٹی کے ماحول (زیادہ نامیاتی مادہ، زیادہ مائکروبیل سرگرمی) میں فصلیں قدرتی طور پر زیادہ پھلتی پھولتی ہیں۔",
        aboutPractice4Title: "تنوع کیوں ضروری ہے؟",
        aboutPractice4Desc: "کاشتکاری کے نظام میں تنوع کو فروغ دینے سے حیاتیاتی تنوع (biodiversity) میں اضافہ ہوتا ہے اور زمین کے استعمال کی کارکردگی اور مجموعی پیداوار میں بہتری آتی ہے۔ تنوع کاربن کے جذب ہونے میں بھی مددگار ہے، خاص طور پر جب درخت شامل ہوں۔ PQNK نظام میں فصلوں کے تنوع کے لیے متعدد حکمت عملیوں پر غور کرنا ضروری ہے — جیسے سیزن کے درمیان کور کراپس، انٹر کراپنگ، اور الے کراپنگ۔",
        aboutPractice5Title: "مشین سازی کیا ہے؟",
        aboutPractice5Desc: "پداور (Pedaver) نے مشینی طور پر اٹھائے ہوئے بیڈز اور نالیاں بنانے اور بھاری ملچ کے ذریعے درست فاصلے پر مشینی براہِ راست کاشتکاری کے لیے مشینری تیار کی ہے۔ پداور کی ایجادات کی بدولت مستقل بغیر ہل چلائے بیڈز پر پودوں کی منتقلی (transplanting) بھی ممکن ہے۔ حالیہ مشینری تو ایک ہی بار میں مستقل بیڈز بنانے اور بیج بونے کی اجازت دیتی ہے۔",
        aboutMissionTitle: "ہمارا مشن",
        aboutMission0Title: "ماہرانہ علم کی وسعت",
        aboutMission0Desc: "ڈاکٹر شریف کی PQNK مہارت کو ڈیجیٹل بنانا — تاکہ پاکستان کے ہر کسان کو اردو اور انگریزی میں 24/7 رسائی حاصل ہو سکے۔",
        aboutMission1Title: "AI کے ذریعے رسائی",
        aboutMission1Desc: "RAG پر مبنی AI کے ذریعے، قابل اعتماد اور حقیقت پر مبنی زرعی رہنمائی فراہم کرنا جو مکمل طور پر PQNK علم پر مبنی ہو۔",
        aboutMission2Title: "پائیدار زراعت",
        aboutMission2Desc: "پاکستان کی 37٪ زرعی افرادی قوت کو ایسے آلات سے لیس کرنا جو کیمیائی کاشتکاری سے قدرتی اور پائیدار طریقوں کی طرف منتقل ہو سکیں۔",
        aboutFounderTitle: "بانی سے ملئیے",
        aboutFounderHeroTitle: "ایک انقلابی موجد",
        aboutFounderName: "مسٹر آصف شریف",
        aboutFounderRole: "بانی اور چئیرمین — پداور",
        aboutFounderBio1: "مسٹر آصف شریف ایک دور اندیش اور تخلیقی زرعی علمبردار، کاروباری شخصیت، انجینئر، موجد اور مخیر انسان ہیں۔ فیصل آباد کے معزز سرگروہ خاندان میں پیدا ہوئے جو تعلیم، زراعت اور سماجی خدمت میں اپنی خدمات کے لیے مشہور ہے، مسٹر شریف نے خاندان کی اس میراث کو برقرار رکھا ہے۔",
        aboutFounderBio2: "ان کی مہارت میں مارکیٹینگ، زراعت میں پراجیکٹ ڈویلپمنٹ، پیداواری عمل کی ترقی اور مشین سازی، فارورڈ انجینئرنگ، متبادل توانائیاں، اور ذمہ دارانہ شہریت شامل ہیں۔ انہوں نے مشینی نظام، انتظام، فارم ڈیزائن اور آبپاشی کے بہترین پروگراموں کے ذریعے بے شمار فارمز کو تبدیل کیا ہے۔",
        aboutFounderMachineryTitle: "مشینری اور ایجادات",
        aboutFounderMachineryDesc1: "مسٹر شریف نے متعدد ایجادات کے ساتھ زرعی صنعت میں انقلاب برپا کر دیا ہے۔ انہوں نے مٹی کھرچنے والی مشینوں (scrapers)، فائن لیولر، ریجر، ریورسیبل ڈسک پلو، پلیٹ پلانٹرز، ٹریکٹر پر نصب سپرے کرنے والی مشینیں، گنے کے پلانٹرز، ہارسٹر اور کپاس چننے والی مشینوں سمیت بہت سی زرعی مشینری ڈیزائن اور تیار کی۔",
        aboutFounderMachineryDesc2: "ان کی تخلیقی صلاحیتوں میں زمین کی ہمواری کے آلات، کسٹمائزڈ لیزر لیولنگ، اٹھے ہوئے بیڈ پر کاشتکاری، درست بیج بونے کی مشینیں (precision seeding)، کھاد ڈالنے والے آلات اور مٹی کی ہوا دہی (aeration) کی مشینیں شامل ہیں۔",
        aboutFounderInitiativesTitle: "انقلابی اقدامات",
        aboutFounderInitiativesDesc1: "مسٹر شریف نے ہزاروں سال پرانے ہل چلانے والے روایتی پیداواری عمل کو چیلنج کیا۔ انہوں نے PQNK نظام تیار کیا جس میں ہل چلانے یا زرعی کیمیکلز کی ضرورت نہیں ہوتی اور پانی کے استعمال میں 70٪ سے زیادہ کمی آتی ہے۔ یہ نظام دنیا کا بہترین اور سستا کھانا پیدا کرنے کی صلاحیت رکھتا ہے۔",
        aboutFounderInitiativesDesc2: "انہوں نے نمی والی مٹی میں اٹھے ہوئے بیڈز پر چاول اگانے کا طریقہ تیار کیا، جس سے پانی کے استعمال میں 70٪ کمی آئی۔ مزید برآں، انہوں نے 'ون ایکڑ پراسپیرٹی' (OAP) کے عمل کی قیادت کی، جس سے چھوٹے زمینداروں کو مالی طور پر آزاد ہونے میں مدد ملی۔",
        aboutTimelineTitle: "کیریئر کا ٹائم لائن",
        aboutBusinessTitle: "کاروبار اور سفارت کاری",
        aboutBusinessDesc1: "اپنی تکنیکی مہارت کے علاوہ، مسٹر شریف نے کاروبار اور زراعت میں اہم خدمات انجام دی ہیں۔ انہوں نے پاکستان-بیلجیم بزنس ڈویلپمنٹ فورم کے صدر، جمہوریہ پولینڈ کے اعزازی قونصل اور زرعی ترقیاتی بینک کے بورڈ آف ڈائریکٹرز کے رکن کے طور پر خدمات انجام دیں۔",
        aboutBusinessDesc2: "انہوں نے فورڈ موٹر کمپنی، کیس آئی ایچ (Case IH)، اور کین ووڈ (Kenwood) جیسی مشہور عالمی کمپنیوں کو پاکستان میں متعارف کرانے میں اہم کردار ادا کیا۔",
        aboutPhilanthropyTitle: "فلاح و بہبود اور اقدار",
        aboutPhilanthropyDesc1: "مسٹر شریف ایک عالمی شہری ہیں جنہوں نے امریکہ، آسٹریلیا اور یورپ میں تربیت حاصل کی ہے۔ وہ پانچ براعظموں کا سفر کر چکے ہیں۔ وہ ایک قابلِ اعتماد اور ہمدرد لیڈر ہیں جنہوں نے اپنے ساتھیوں اور کمیونٹیز کا احترام حاصل کیا ہے۔",
        aboutPhilanthropyDesc2: "وہ خاص طور پر جانوروں کی فلاح و بہبود، مٹی کے جانداروں اور زندگی کی تمام شکلوں کے بارے میں پرجوش ہیں — جو زراعت سے ہٹ کر ماحولیاتی پاسداری کے ایک جامع فلسفے کی عکاسی کرتے ہیں۔",
        aboutCollaborationTitle: "کے تعاون سے",

        // ── Contact Us ──────────────────────────────────────────────
        contactHeroBadge: "📬 ہم سے رابطہ کریں",
        contactHeroTitle: "رابطے میں رہیں",
        contactHeroDesc: "PQNK، پلیٹ فارم، تعاون کے مواقع، یا تحقیقی پوچھ گچھ کے بارے میں سوالات ہیں؟ ہم آپ سے سننا پسند کریں گے — آئیے بات شروع کرتے ہیں۔",
        contactInfoTitle: "رابطے کی معلومات",
        contactLabel0: "وابستہ ادارہ",
        contactLabel1: "صنعتی پارٹنر",
        contactLabel2: "تحقیقی پوچھ گچھ",
        contactLabel3: "تعلیمی کانفرنس",
        contactFollowTitle: "ہماری تحقیق فالو کریں",
        contactFormTitle: "ہمیں پیغام بھیجیں",
        contactFormIntro: "تمام فیلڈز جن پر * لگا ہے وہ لازمی ہیں۔",
        contactFirstName: "پہلا نام",
        contactLastName: "آخری نام",
        contactEmail: "ای میل ایڈریس",
        contactPhone: "فون نمبر",
        contactSubject: "موضوع",
        contactMessage: "پیغام",
        contactSubjectSelect: "موضوع منتخب کریں…",
        contactSubjectGeneral: "عام انکوائری",
        contactSubjectPQNK: "PQNK کاشتکاری طریقہ کار",
        contactSubjectResearch: "تحقیقی اور تعلیمی تعاون",
        contactSubjectTechnical: "پلیٹ فارم / تکنیکی مدد",
        contactSubjectMedia: "میڈیا اور پریس",
        contactSubjectOther: "دیگر",
        contactSendBtn: "📤 پیغام بھیجیں",
        contactSendingBtn: "بھیجا جا رہا ہے…",
        contactSuccessTitle: "پیغام بھیج دیا گیا!",
        contactSuccessDesc: "رابطہ کرنے کا شکریہ۔ ہماری ٹیم آپ کے پیغام کا جائزہ لے گی اور 2-3 کاروباری دنوں میں جواب دے گی۔",
        contactAnotherBtn: "ایک اور پیغام بھیجیں",

        // ── Profile ────────────────────────────────────────────────
        profileTitle: "میری پروفائل",
        profileDesc: "اپنے اکاؤنٹ کی معلومات اور اسناد کا انتظام کریں",
        profileMemberSince: "رکنیت کی تاریخ",
        profileStatus: "حیثیت",
        profileOnline: "آن لائن",
        profileAccountDetails: "اکاؤنٹ کی تفصیلات",
        profileEditBtn: "✏️ پروفائل ایڈٹ کریں",
        profileUpdateSuccess: "پروفائل کامیابی سے اپ ڈیٹ ہو گئی!",
        profileUpdateFail: "اپ ڈیٹ ناکام ہو گیا",
        profileServerErr: "سرور سے رابطہ نہیں ہو سکا",
        profileFullName: "پورا نام",
        profileEmailLock: "ای میل ایڈریس (تبدیل نہیں کیا جا سکتا)",
        profileChangePass: "پاس ورڈ تبدیل کریں (موجودہ رکھنے کے لیے خالی چھوڑ دیں)",
        profileCurrentPass: "موجودہ پاس ورڈ",
        profileNewPass: "نیا پاس ورڈ",
        profileConfirmPass: "نئے پاس ورڈ کی تصدیق کریں",
        profileSaveBtn: "ترمیم محفوظ کریں",
        profileCancelBtn: "منسوخ کریں",
        profileSavingBtn: "محفوظ ہو رہا ہے…",
        profilePassMismatch: "نئے پاس ورڈ مطابقت نہیں رکھتے",

        // ── User Survey ────────────────────────────────────────────
        surveyTitle: "آپ کو بہتر طور پر سمجھنے میں ہماری مدد کریں",
        surveyTitleDone: "✅ سروے مکمل ہوا — شکریہ!",
        surveyDesc: "کسانوں کی بہتر خدمت کرنے میں ہماری مدد کے لیے ایک مختصر 6 سوالات کا سروے (2 منٹ)",
        surveyDescDone: "آپ کے جوابات محفوظ کر لیے گئے ہیں۔ جائزہ لینے یا اپ ڈیٹ کرنے کے لیے کلک کریں۔",
        surveyUpdateMsg: "✅ آپ کے جوابات محفوظ ہیں۔ آپ کسی بھی وقت انہیں اپ ڈیٹ کر سکتے ہیں۔",
        surveyQ1: "1. فارم / زمین کا سائز",
        surveyQ1Select: "زمین کا سائز منتخب کریں…",
        surveyQ1Opt1: "1 ایکڑ سے کم",
        surveyQ1Opt2: "1 – 5 ایکڑ",
        surveyQ1Opt3: "5 – 20 ایکڑ",
        surveyQ1Opt4: "20 – 50 ایکڑ",
        surveyQ1Opt5: "50 ایکڑ سے زیادہ",
        surveyQ1Opt6: "کوئی زمین نہیں (طالب علم / محقق)",
        surveyQ2: "2. اگائی جانے والی بنیادی فصلیں (تمام متعلقہ منتخب کریں)",
        surveyQ3: "3. کاشتکاری کا سب سے بڑا چیلنج",
        surveyQ3Select: "بنیادی چیلنج منتخب کریں…",
        surveyQ3Opt1: "پانی کی رسائی / آبپاشی",
        surveyQ3Opt2: "کیڑے اور بیماریوں کا کنٹرول",
        surveyQ3Opt3: "مٹی کی صحت / زرخیزی",
        surveyQ3Opt4: "مارکیٹ تک رسائی / قیمتیں",
        surveyQ3Opt5: "مالی معاونت / کریڈٹ",
        surveyQ3Opt6: "زرعی علم کی کمی",
        surveyQ3Opt7: "موسمیاتی تبدیلی / موسم",
        surveyQ3Opt8: "لیبر کی دستیابی",
        surveyQ3Opt9: "دیگر",
        surveyQ4: "4. آپ نے PQNK / ایگری چیٹ کے بارے میں کیسے سنا؟",
        surveyQ4Select: "ذریعہ منتخب کریں…",
        surveyQ4Opt1: "مسٹر آصف شریف کی یوٹیوب ویڈیو",
        surveyQ4Opt2: "واٹس ایپ گروپ / براڈکاسٹ",
        surveyQ4Opt3: "PAR فیلڈ ورکر / تقریب",
        surveyQ4Opt4: "کسی کسان یا دوست سے",
        surveyQ4Opt5: "سوشل میڈیا (فیس بک، انسٹاگرام)",
        surveyQ4Opt6: "یونیورسٹی / تعلیمی حوالہ",
        surveyQ4Opt7: "پداور / فیلڈ ڈیموسٹریشن",
        surveyQ4Opt8: "دیگر",
        surveyQ5: "5. کاشتکاری کا تجربہ (سالوں میں)",
        surveyQ5Select: "تجربہ منتخب کریں…",
        surveyQ5Opt1: "کاشتکاری کا کوئی تجربہ نہیں",
        surveyQ5Opt2: "1 – 3 سال",
        surveyQ5Opt3: "3 – 10 سال",
        surveyQ5Opt4: "10 – 25 سال",
        surveyQ5Opt5: "25 سال سے زیادہ",
        surveyQ6: "6. پڑھنے / خواندگی کی سطح (ہمیں پلیٹ فارم کو آپ کے لیے بہتر بنانے میں مدد ملتی ہے)",
        surveyQ6Opt1: "میں انگریزی یا اردو میں آسانی سے پڑھ اور لکھ سکتا ہوں",
        surveyQ6Opt2: "میں جزوی طور پر پڑھنا جانتا ہوں — میں سادہ زبان کو ترجیح دیتا ہوں",
        surveyQ6Opt3: "میں آڈیو جوابات کو ترجیح دیتا ہوں — میں پڑھنے کے بجائے سننے پر انحصار کرتا ہوں",
        surveySubmitBtn: "✅ سروے جمع کروائیں",
        surveyUpdateBtn: "💾 سروے کے جوابات اپ ڈیٹ کریں",

        // ── Chatbot ──────────────────────────────────────────────
        newConversation: "نئی گفتگو",
        quickTopics: "تیز موضوعات",
        recentConversations: "حالیہ گفتگوئیں",
        noConversations: "کوئی پرانی گفتگو نہیں",
        online: "آن لائن · PQNK انٹیلی ایگری",
        welcomeTitle: "ایگری چیٹ میں خوش آمدید",
        welcomeBody: "میں فصلوں، مٹی، آبپاشی، موسمیاتی موافقت اور کیٹ مار ادویات سے متعلق جامع زرعی ڈیٹا پر تربیت یافتہ ہوں۔ بنیادی کاشتکاری سے لے کر جدید زرعی منصوبہ بندی تک کچھ بھی پوچھیں۔",
        placeholder: "اپنا پیغام ٹائپ کریں…",
        thinking: "ایگری چیٹ سوچ رہا ہے…",
        enterHint: "بھیجنے کے لیے Enter دبائیں",
        recording: "ریکارڈ ہو رہا ہے… روکنے کے لیے مائیک ٹیپ کریں",
        transcribing: "تحریر ہو رہا ہے…",
        voiceErr: "آواز درج نہیں ہوئی۔ دوبارہ کوشش کریں۔",
        suggestedQ: "تجویز کردہ سوالات",
        topicCrop: "فصل کا مسئلہ",
        topicWater: "آبپاشی کا وقت؟",
        topicFert: "کھاد کی معلومات",
        topicPest: "کیڑوں کا کنٹرول",
        promptWheat: "گندم کی آبپاشی",
        promptSoil: "مٹی کی صحت",
        promptPest: "کپاس کے کیڑے",
        promptRice: "چاول کی پیداوار",
        promptNursery: "نرسری کی دیکھ بھال",
        queryCrop: "میری فصل میں ایک مسئلہ ہے۔ کیا آپ اس کی تشخیص میں مدد کر سکتے ہیں؟",
        queryWater: "میری موجودہ فصلوں کے لیے آبپاشی کا بہترین شیڈول کیا ہے؟",
        queryFert: "مٹی کی بہتر صحت کے لیے مجھے کھادوں کا انتظام کیسے کرنا چاہیے؟",
        queryPest: "وہ کون سے عام کیڑے ہیں جن سے مجھے ہوشیار رہنا چاہیے اور انہیں کیسے کنٹرول کیا جائے؟",
        queryWheat: "PQNK سسٹم میں گندم کی فصلوں کے لیے آبپاشی کا بہترین شیڈول کیا ہے؟",
        querySoil: "کیمیائی کھادوں کے بغیر میں قدرتی طور پر مٹی کی زرخیزی کو کیسے بہتر بنا سکتا ہوں؟",
        queryPestCot: "پاکستان میں کپاس کی فصلوں کے لیے نامیاتی کیٹ کنٹرول کے طریقے کیا ہیں؟",
        queryRice: "مستقل اٹھائے ہوئے بیڈز کا استعمال کرتے ہوئے میں چاول کی فصل کی پیداوار کو کیسے بہتر بنا سکتا ہوں؟",
        queryNursery: "پودوں کی دیکھ بھال اور نرسری مینجمنٹ کے بہترین طریقے کیا ہیں؟",
        
        // ── Auth Pages ─────────────────────────────────────────────
        authWelcomeBack: "خوش آمدید",
        authSignInDesc: "اپنے ڈیش بورڈ پر جانے کے لیے سائن ان کریں",
        authEmailLabel: "ای میل ایڈریس",
        authEmailPlaceholder: "you@example.com",
        authPasswordLabel: "پاس ورڈ",
        authForgotPassword: "پاس ورڈ بھول گئے؟",
        authRememberMe: "مجھے یاد رکھیں",
        authSignInBtn: "سائن ان کریں",
        authSigningIn: "سائن ان ہو رہا ہے…",
        authOr: "یا",
        authNoAccount: "کیا آپ کا اکاؤنٹ نہیں ہے؟",
        authCreateAccount: "اکاؤنٹ بنائیں",
        
        authCreateTitle: "اکاؤنٹ بنائیں",
        authCreateDesc: "قدرتی کاشتکاری کی معلومات کے لیے PQNK میں شامل ہوں۔",
        authFullName: "پورا نام",
        authFullNamePlace: "ڈاکٹر آصف شریف",
        authPhoneLabel: "فون نمبر",
        authPhonePlace: "0300 1234567",
        authConfirmPassword: "پاس ورڈ کی تصدیق کریں",
        authAgreeTerms1: "میں",
        authAgreeTerms2: "شرائط و ضوابط",
        authAgreeTerms3: "اور",
        authAgreeTerms4: "پرائیویسی پالیسی سے متفق ہوں",
        authSignUpBtn: "اکاؤنٹ بنائیں",
        authSigningUp: "اکاؤنٹ بن رہا ہے…",
        authHaveAccount: "کیا آپ کا پہلے سے اکاؤنٹ ہے؟",
        authLoginLink: "لاگ ان کریں",
        
        authVerifyTitle: "اپنے اکاؤنٹ کی تصدیق کریں",
        authVerifyDesc1: "ہم نے ایک 6 ہندسوں کا تصدیقی کوڈ اس پر بھیجا ہے:",
        authVerifyDesc2: "اپنا اکاؤنٹ فعال کرنے کے لیے اسے نیچے درج کریں۔",
        authCodeLabel: "تصدیقی کوڈ",
        authVerifyBtn: "اکاؤنٹ کی تصدیق کریں",
        authVerifying: "تصدیق ہو رہی ہے…",
        authDidntReceive: "کوڈ موصول نہیں ہوا؟",
        authResendBtn: "دوبارہ کوڈ بھیجیں",
        authResending: "بھیجا جا رہا ہے…",
        authBackToLogin: "لاگ ان پر واپس جائیں",
        
        authResetTitle: "پاس ورڈ ری سیٹ کریں",
        authResetDesc: "اپنا ای میل ایڈریس درج کریں اور ہم آپ کا پاس ورڈ ری سیٹ کرنے کے لیے 6 ہندسوں کا کوڈ بھیجیں گے۔",
        authSendCodeBtn: "ری سیٹ کوڈ بھیجیں",
        authSendingCode: "بھیجا جا رہا ہے…",
        authVerifyResetTitle: "تصدیق کریں اور ری سیٹ کریں",
        authVerifyResetDesc: "اپنی ای میل پر بھیجا گیا کوڈ اور نیا پاس ورڈ درج کریں۔",
        authResetNewPass: "نیا پاس ورڈ",
        authResetBtn: "پاس ورڈ ری سیٹ کریں",
        authResetting: "ری سیٹ ہو رہا ہے…",
    },
};
